//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace komproject.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cooling()
        {
            this.PC = new HashSet<PC>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Price { get; set; }
        public string Socket { get; set; }
        public string Fandimensions { get; set; }
        public string Fanspeed { get; set; }
        public string Noiselevel { get; set; }
        public string Material { get; set; }
        public string Rotationalspeedmax { get; set; }
        public string Fanconnector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC> PC { get; set; }
    }
}
