//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace komproject.DataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RasulpcEntities1 : DbContext
    {
        public RasulpcEntities1()
            : base("name=RasulpcEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<CaseForm> CaseForm { get; set; }
        public virtual DbSet<Cooling> Cooling { get; set; }
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<CPUmanufacturer> CPUmanufacturer { get; set; }
        public virtual DbSet<HDD> HDD { get; set; }
        public virtual DbSet<IdSocket> IdSocket { get; set; }
        public virtual DbSet<memorytype> memorytype { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<PC> PC { get; set; }
        public virtual DbSet<pcpowersupply> pcpowersupply { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SSD> SSD { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Videocard> Videocard { get; set; }
    }
}
