//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace komproject.DataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC()
        {
            this.User1 = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int IdCPU { get; set; }
        public int IdMotherboard { get; set; }
        public int IdVideocard { get; set; }
        public int IdRAM { get; set; }
        public int IdPCPOWERSupplyUNIT { get; set; }
        public int IdHDD { get; set; }
        public int IdSSD { get; set; }
        public int IdCooling { get; set; }
        public int IdCase { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> likes { get; set; }
        public Nullable<int> rel { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Cooling Cooling { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual HDD HDD { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual pcpowersupply pcpowersupply { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual SSD SSD { get; set; }
        public virtual User User { get; set; }
        public virtual Videocard Videocard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User1 { get; set; }
    }
}
